---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[tdc::default]

  - name: users
    run_list:
      - recipe[tdc::users]

