source "https://rubygems.org"

gem 'berkshelf'
gem "docker"
gem 'berkshelf'
gem 'chefspec'
gem 'kitchen'
gem "kitchen-docker"
gem 'kitchen-nodes'
gem 'knife-spork'
gem 'rubocop'
gem 'foodcritic'
gem 'serverspec'